name: Build, Security Scan and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Trivy Scan and SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # 3️⃣ Cache Sonar
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 4️⃣ Cache Maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 5️⃣ Build
      - name: Build project
        run: mvn -B verify -Dmaven.test.failure.ignore=true

      # 6️⃣ Trivy FS JSON
      - name: Trivy FS Scan (JSON)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          format: json
          output: trivy-fs-report.json
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      # 7️⃣ Trivy Image JSON
      - name: Trivy Image Scan (JSON)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: salam630/jpetstore-groupe-app:latest
          format: json
          output: trivy-image-report.json
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      # 8️⃣ Télécharger template HTML
      - name: Download Trivy HTML template
        run: curl -LO https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      # 9️⃣ Convert FS JSON → HTML (une seule fois)
      - name: Convert FS report to HTML
        run: |
          trivy convert \
            --format template \
            --template html.tpl \
            -o trivy-fs-report.html \
            trivy-fs-report.json

      # 10️⃣ Upload HTML Reports
      - name: Upload Trivy HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-html-reports
          path: |
            trivy-fs-report.html
            trivy-image-report.html

      # 11️⃣ SonarQube
      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=TP-Sonarqube \
            -Dsonar.projectName='TP-Sonarqube' \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
